COMMON:
  SAVEPATH: ./log/test
  GPUS: [0]
  SEED: 42

DATA:
  NAME: dogbreed
  INPUTSIZE: 256
  BATCHSIZE: 64
  NUMWORKER: 2

MODEL:
  BASEMODEL: efficientnet_b0
  NUMCLASSES: 121
  FREEZE: true

TRAIN:
  OPTIMIZER: sgd
  LEARNINGRATE: 0.001
  EPOCHS: 5
