COMMON:
  SAVEPATH: ./log
  GPUS: [0]
  SEED: 42

DATA:
  ROOT: ./data
  NAME: flower_photos
  INPUTSIZE: 64
  BATCHSIZE: 64
  NUMWORKER: 2

MODEL:
  BASEMODEL: efficientnet_b0
  NUMCLASSES: 5
  FREEZE: true
  ARCFACE: true

TRAIN:
  OPTIMIZER: adam
  LEARNINGRATE: 0.001
  EPOCHS: 2